name: DeepVLF
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.0
  - pip=23.3
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - pip:
    - numpy==1.26.4
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - tqdm==4.66.2

